"""empty message

Revision ID: 045edb194b4a
Revises: c8f8edc1dcaa
Create Date: 2025-03-22 11:37:47.196404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045edb194b4a'
down_revision = 'c8f8edc1dcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage_agency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_grp', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage_agency', schema=None) as batch_op:
        batch_op.drop_column('code_grp')

    # ### end Alembic commands ###
