"""empty message

Revision ID: 1085a9e15489
Revises: 50170908b2b9
Create Date: 2025-03-20 12:12:34.712455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1085a9e15489'
down_revision = '50170908b2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_places', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.drop_column('nb_places')

    # ### end Alembic commands ###
