"""empty message

Revision ID: 18073feea977
Revises: 045edb194b4a
Create Date: 2025-03-22 12:49:08.974696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18073feea977'
down_revision = '045edb194b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_grp', sa.String(length=50), nullable=False))

    with op.batch_alter_table('voyage_agency', schema=None) as batch_op:
        batch_op.drop_column('code_grp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage_agency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_grp', mysql.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.drop_column('code_grp')

    # ### end Alembic commands ###
