"""empty message

Revision ID: 2195388e4516
Revises: 476c8064a564
Create Date: 2024-12-05 19:34:27.125142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2195388e4516'
down_revision = '476c8064a564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bus_included', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_visa_included', sa.Boolean(), nullable=True))

    with op.batch_alter_table('voyage_include', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rest_to_pay', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage_include', schema=None) as batch_op:
        batch_op.drop_column('rest_to_pay')
        batch_op.drop_column('total_paid')

    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.drop_column('is_visa_included')
        batch_op.drop_column('is_bus_included')

    # ### end Alembic commands ###
