"""empty message

Revision ID: 29dcdc38d112
Revises: a91afbf6e758
Create Date: 2024-11-21 17:06:20.541220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dcdc38d112'
down_revision = 'a91afbf6e758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('include', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_hotel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hotel', ['fk_hotel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('include', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_hotel_id')

    # ### end Alembic commands ###
