"""empty message

Revision ID: 2d3b4058466b
Revises: 2195388e4516
Create Date: 2024-12-05 19:40:47.648418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d3b4058466b'
down_revision = '2195388e4516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plane_fees', sa.Integer(), nullable=True))
        batch_op.drop_column('avion_fees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avion_fees', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('plane_fees')

    # ### end Alembic commands ###
