"""empty message

Revision ID: 436939ab19d7
Revises: 7aa838663df5
Create Date: 2024-12-07 20:13:50.955317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '436939ab19d7'
down_revision = '7aa838663df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.drop_column('bus_company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bus_company', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
