"""empty message

Revision ID: 476c8064a564
Revises: 69d148872f01
Create Date: 2024-11-26 19:29:02.190140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476c8064a564'
down_revision = '69d148872f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
