"""empty message

Revision ID: 50170908b2b9
Revises: 436939ab19d7
Create Date: 2025-03-20 11:51:33.547412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50170908b2b9'
down_revision = '436939ab19d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('code')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
