"""empty message

Revision ID: 7aa838663df5
Revises: fedccfe397b7
Create Date: 2024-12-05 22:01:04.797936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa838663df5'
down_revision = 'fedccfe397b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.drop_column('subscription_due_date')

    # ### end Alembic commands ###
