"""empty message

Revision ID: 90d54b031f2d
Revises: 0c0ace79118e
Create Date: 2024-10-30 18:24:15.108601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90d54b031f2d'
down_revision = '0c0ace79118e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=mysql.SMALLINT(display_width=6),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.Boolean(),
               type_=mysql.SMALLINT(display_width=6),
               existing_nullable=True)

    # ### end Alembic commands ###
