"""empty message

Revision ID: a91afbf6e758
Revises: 8f62868d0c64
Create Date: 2024-11-21 10:16:22.531497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91afbf6e758'
down_revision = '8f62868d0c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'person', ['fk_person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_person_id')

    # ### end Alembic commands ###
