"""empty message

Revision ID: c0c2ce9c24d3
Revises: 64fcabcf96d3
Create Date: 2025-04-02 21:27:11.061376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c2ce9c24d3'
down_revision = '64fcabcf96d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_submitted_for_payment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.drop_column('is_submitted_for_payment')

    # ### end Alembic commands ###
