"""empty message

Revision ID: d868d3caf671
Revises: 1085a9e15489
Create Date: 2025-03-20 12:20:24.503454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd868d3caf671'
down_revision = '1085a9e15489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voyage', sa.Column('nb_free_places', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voyage', 'nb_free_places')
    # ### end Alembic commands ###
