"""empty message

Revision ID: e8093ae822be
Revises: d868d3caf671
Create Date: 2025-03-20 12:25:05.772012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8093ae822be'
down_revision = 'd868d3caf671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('responsible_full_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency', 'responsible_full_name')
    # ### end Alembic commands ###
